name = "Client+"
author = "Thijzert"
version = "1.0.0+1.21.1-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54ae3ab8dcf0c5192ce879fb868fa100b8a8ffab9f1a86c4bc64df8fe4552483"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
