name = "Server+"
author = "Thijzert"
version = "1.0.0+1.21.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57b4b0fcd835fca3aa96d5c2d9c7da479899c3053325d800ebb6c9bb42ff35de"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
