name = "Server+"
author = "Thijzert"
version = "1.0.0+1.20.1-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5f790c72b083365870eb1ccdc6e0d57e577d10c875f49a0181a181e74e0e88f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
