name = "Server+"
author = "Thijzert"
version = "1.0.0+1.20.1-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fed6f8e8b9ebc95f908af888ea645f4d420843ca6bbcb334293cec650a13edb"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
