name = "Server+"
author = "Thijzert"
version = "1.0.0+1.20.1-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed58312a74d726f4c99641264ca69139547d26d27263676f343a3be5bbde1545"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
