name = "Server+"
author = "Thijzert"
version = "1.0.0+1.21.4-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50343e94dd9833179d64d6ace9ab3ad42d679db31d53e025d565e7cec4b211a1"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
