name = "Server+"
author = "Thijzert"
version = "1.0.0+1.21.4-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af044f6fda701a9696391280ede790ff4002221dd1b265cea31f242baa229037"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
