name = "Server+"
author = "Thijzert"
version = "1.0.0+1.20.4-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c53f774a5c89e71240806d7bf5d8b6753f43d451a5cfc53f4195b6d7e606fbc3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
