name = "Server+"
author = "Thijzert"
version = "1.0.0+1.20.4-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b648598b72fa3ff87da2240d52cdce48b015d85e044b87d69f17a2859bb17fe"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
