name = "Server+"
author = "Thijzert"
version = "1.0.0+1.20.4-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d0b050af1264a47cd1135a84cb6fab737cad9ffd8ecc66be64cd66847d3df3e"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
