name = "Server+"
author = "Thijzert"
version = "1.0.0+1.20.4-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8aaa5672c1d39d97019c4b752a6e51d3f83d12c5a1ad00831eaa86a5db0f6e1d"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
