name = "Server+"
author = "Thijzert"
version = "1.0.0+1.21.3-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aea287469bd1011f4e192d925e14582e243c3b681084c60768cb5dcdcf3d09d0"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
