name = "Server+"
author = "Thijzert"
version = "1.0.0+1.21.3-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3bbc374311c945d57705f3cd37f619850e827a8b23d35bc8337e77d691e634c"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
