name = "Server+"
author = "Thijzert"
version = "1.0.0+1.21.3-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fcf0cbec3ebcb1d35aebd4848d2dbe00ef3ad07920613a82fba5ad37cb50dca"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
